version: '3'

volumes:
  postgres_volume:

services:
  db:
    image: postgres:14-alpine3.17
    env_file:
      - ./auth/.env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  auth-migratior:
    build:
      context: ./auth
      dockerfile: migration.Dockerfile
    env_file:
      - "./auth/migration.env"
    depends_on:
      - db
    restart: on-failure

  auth-server:
    image: cr.selcloud.ru/sarastee/auth-server:${TAG_NAME}
    env_file:
      - "./auth/.env"
    ports:
      - "50051:50051"
    depends_on:
      - db